name: rental_room
description: "A Rental Room project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  firebase_core: 3.6.0
  firebase_auth: 5.2.0
  cloud_firestore: 5.4.0
  firebase_storage: 12.3.0
  firebase_app_check: 0.3.1+4
  google_sign_in: ^6.2.2

  provider: ^6.1.5
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  path_provider: ^2.1.5
  package_info_plus: ^8.0.0
  google_maps_flutter: ^2.10.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1

  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  uuid: ^4.5.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/img/Auth1.jpg
    - lib/img/Auth2.jpg
    - lib/img/gg.png
